services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  # api:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - REDIS_URL=redis://redis:6379
  #     - ADO_ORGANIZATION=thecollege
  #     - AZURE_PAT=your_pat_here
  #     - AZURE_API_VERSION=7.1-preview.3
  #   depends_on:
  #     - redis
